INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI HAVAÍ (kg)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (6.50 kg)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (cx 10 un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (kg)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (kg)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (kg)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (t)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (t)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (t)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (t)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (t)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI PÉROLA (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI TERRA DE AREIA (cx 10 un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ABACAXI (un)', 'abacaxi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇAÍ FRUTO (kg)', 'açaí');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇAÍ FRUTO (kg)', 'açaí');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇAÍ FRUTO (kg)', 'açaí');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇAÍ FRUTO (kg)', 'açaí');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (10 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (20 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (2 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (2 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (2 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (2 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (30 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (30 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (30 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (30 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (30 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (30 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (50 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (5 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (5 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (5 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR CRISTAL (kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR REFINADO (10 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AÇÚCAR REFINADO (10 kg)', 'açúcar');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM CAROÇO (15 kg)', 'algodão em caroço');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM CAROÇO (15 kg)', 'algodão em caroço');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM CAROÇO (15 kg)', 'algodão em caroço');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM CAROÇO TIPO BÁSICO - SLM 41-4 BRANCO (15 kg)', 'algodão em caroço');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM PLUMA (15 kg)', 'algodão em pluma');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM PLUMA (15 kg)', 'algodão em pluma');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM PLUMA (15 kg)', 'algodão em pluma');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM PLUMA (15 kg)', 'algodão em pluma');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM PLUMA TIPO BÁSICO - SLM 41-4 BRANCO (15 kg)', 'algodão em pluma');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM PLUMA TIPO BÁSICO - SLM 41-4 BRANCO (15 kg)', 'algodão em pluma');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALGODÃO EM PLUMA TIPO BÁSICO - SLM 41-4 BRANCO (15 kg)', 'algodão em pluma');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO CHINÊS (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO COMUM (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO COMUM (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO COMUM (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO COMUM (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO NACIONAL (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO NOBRE (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO NOBRE ROXO EXTRA (kg) (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO NOBRE T 5 (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO COMUM (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE 4 (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE 5 (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE 5 (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE 5 (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE 5 (kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE 6 (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE 7 (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE COMERCIAL T5 (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE COMERCIAL T5 (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ALHO ROXO NOBRE ESPECIAL T5 (10 kg)', 'alho');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMÊNDOA DE ANDIROBA (kg)', 'amêndoa de andiroba');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMÊNDOA DE BARU (kg)', 'amêndoa de baru');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMÊNDOA DE BARU (kg)', 'baru');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMÊNDOA DE CACAU (15 kg)', 'amêndoa de cacau');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMÊNDOA DE CACAU (15 kg)', 'cacau');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMÊNDOA DE CACAU (60 kg)', 'amêndoa de cacau');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMÊNDOA DE CACAU (60 kg)', 'cacau');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMÊNDOA DE CACAU (kg)', 'amêndoa de cacau');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMÊNDOA DE CACAU (kg)', 'cacau');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM DESCASCADO (25 kg)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM DESCASCADO (25 kg)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM DESCASCADO CATADO (50 kg)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM DESCASCADO (kg)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM EM CASCA (25 kg)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM EM CASCA (25 kg)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM EM CASCA (25 kg)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM EM CASCA (30 kg)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM EM CASCA (kg)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AMENDOIM EM CASCA (t)', 'amendoim');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ BENEFICIADO (A) PARBOILIZADO LONGO FINO (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ BENEFICIADO (A) PARBOILIZADO LONGO FINO (30 kg)', 'boi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ BENEFICIADO VERMELHO (10 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ BENEFICIADO VERMELHO (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ EM CASCA (50 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ EM CASCA (50 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ EM CASCA VERMELHO (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO BENEFICIADO (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO BENEFICIADO (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO BENEFICIADO (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO BENEFICIADO A PRAZO (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO BENEFICIADO À VISTA (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO BENEFICIADO À VISTA (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO BENEFICIADO TIPO 1 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO BENEFICIADO TIPO 2 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO EM CASCA (50 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO EM CASCA TIPO 1 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO EM CASCA TIPO 2 55/13 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO A PRAZO (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO À VISTA (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (10 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (25 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (25 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (2 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (50 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (50 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (5 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (5 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (5 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (5 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 1 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (10 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (10 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (25 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 2 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 3 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO BENEFICIADO TIPO 3 (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA (50 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA (50 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA TIPO 1 (50 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA TIPO 1 58/10 (50 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA TIPO 1 58/10 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA TIPO 1 58/10 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA TIPO 1 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA TIPO 2 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA TIPO 2 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO EM CASCA TIPO 3 (60 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO PARBOILIZADO TIPO 1 (kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ LONGO FINO PARBOILIZADO TIPO 1 (kg)', 'boi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ PARBOILIZADO BENEFICIADO (A) 1 (30 kg) (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ PARBOILIZADO BENEFICIADO (A) 1 (30 kg) (30 kg)', 'boi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ PARBOILIZADO BENEFICIADO (A) 1 (30 kg) (30 kg)', 'arroz');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('ARROZ PARBOILIZADO BENEFICIADO (A) 1 (30 kg) (30 kg)', 'boi');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AVEIA EM CASCA (60 kg)', 'aveia');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AVEIA EM CASCA BRANCA (60 kg)', 'aveia');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AVEIA EM CASCA BRANCA (60 kg)', 'aveia');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AZEITE DE BABAÇU (l)', 'azeite de babaçu');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AZEITE DE BABAÇU (l)', 'azeite de babaçu');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AZEITE DE MACAÚBA (l)', 'azeite de macaúba');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('AZEITE DE MACAÚBA (l)', 'macaúba');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BADEJO CONGELADO (kg)', 'badejo');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BAGRE CONGELADO (kg)', 'bagre');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA DA TERRA (1000 un)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA DA TERRA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (22 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (22 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA NANICA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PACOVAN (1000 un)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PACOVAN (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PACOVAN (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (1000 un)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (20 kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (kg)', 'banana');
INSERT INTO Dimensao_Produto (nome_produto, cultura_especie) VALUES ('BANANA PRATA (kg)', 'banana');
